export const GET_ACTIVITY_TYPES = 'GET_ACTIVITY_TYPES';
export const GET_ACTIVITIES_WITH_CODE_TYPE = 'GET_ACTIVITY_WITH_CODE_TYPE';
export const GET_ACTIVITY_WITH_ID = 'GET_ACTIVITY_WITH_ID';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const GET_USER_POINTS = 'GET_USER_POINTS';
export const ADD_TO_FAVUORITES_LIST = 'ADD_TO_FAVORITES_LIST';
export const REMOVE_FROM_FAVUORITES_LIST = 'REMOVE_FROM_FAVUORITES_LIST';
